### ISSUE TITLE
Bamboo provider is never detected

### ISSUE THREAD

**Issue by renanbandeira** [codecov/codecov-bash#336]
I've tried to set all environment variables, but without success. I realized that bamboo variable is overriden on bash script and maybe this is the problem.

**Comment by thomasrockhu** [comment]
@renanbandeira can you provide a repository and build link?

**Comment by renanbandeira** [comment]
Hi @thomasrockhu, my project has confidential terms, but I know the reason why this provider is dever detected (at least I think I do).
https://github.com/codecov/codecov-bash/blob/master/codecov#L80 this line overrides variable used to detect Bamboo. Plus, this is not the variable used by Bamboo (they use dot instead of underlines: https://confluence.atlassian.com/bamboo/bamboo-variables-289277087.html ).

**Comment by thomasrockhu** [comment]
Hi @renanbandeira thanks for the work here, I merged a PR to fix this, and it should be deployed this week.

**Comment by renanbandeira** [comment]
@thomasrockhu thank you! I was almost opening the PR, but I didn't have time to read what I had to do before opening the PR, such as tests and so.

I still have a problem that my PRs aren't receiving Git check status from codecov, but this is another issue and I don't think it is related to this script. Thanks!

**Comment by thomasrockhu** [comment]
@renanbandeira if you open a ticket on our [community boards](https://community.codecov.io), tag me and I can take a look.
